base_url = "https://patryk.guba.pl"
compile_sass = true
title = "Patryk Guba"
description = "Tech posts you wouldn't find anywhere else!"
generate_feeds = true

taxonomies = [
    {name = "categories", feed = false},
    {name = "other_websites", feed = true},
    {name = "tags", feed = true},
]

# When set to "true", a search index is built from the pages and section
# content for `default_language`.
build_search_index = true 

[markdown]
# Whether to do syntax highlighting
# Theme can be customized by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

highlight_theme = "one-dark"

[search]
index_format = "elasticlunr_json"

[extra]
author = "Patryk Guba"
after_dark_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "$BASE_URL/other-websites", name = "Cool websites!"},
]
after_dark_title = "yes"

# Nicer codeblocks with copy to clipboard 
codeblock = true

# Enable MathJax support
latex = true

# Enable search bar 
enable_search = true 
